name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner:
#  build_runner: ^2.4.9
#  retrofit_generator: ^10.2.1
#  injectable_generator: ^2.7.0
  dart_mapper_clean:
    path: ../
