name: dart_mapper

description: Code generator for mapping between Dart model classes using @Mapper-style annotations.
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.4
  source_gen: ^4.2.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.11.0
  lints: ^3.0.0
  test: ^1.25.0


